---
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/movies?useSSL=false"
    username: root
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org.superbiz.moviefun: DEBUG
    org.springframework.web: DEBUG
    root: INFO
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
