spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  awsS3creds:
    access_key_id : AKIAI3EUL5OHTJBAR4PA
    secret_access_key: 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
    bucket :  dell-emc-student-artifacts-3
